### PR TITLE
Android/notification as foreground service

### PR DESCRIPTION
**Pull request by tonydung2011**
Hi @FabienLavocat , I'm one of your Voxeet Conference Service customer. This Pull request is targeted to implement the Fullscreen - Intent service for invitation notification in Android. Please help to review my PR. I'm not a Android developer natively so please open any discussion if you need.

### CODE REVIEW

**Comment by codlab** [comment]
It looks good so far, some things should be fixed :
- the mp3 file is empty but we couldn't use it anyway due to possible copyright restrictions. There is another one which is `out.mp3` and can be used (legacy usage)

- the `InvitationDismissBroadcastReceiver` should be removed, it is used to mimic the `DismissNotificationBroadcastReceiver` which is a part of the native `uxkit` module.

As the only thing this new broadcast receiver does is to send a stop action to the declared service, it can be moved to the `IIncomingInvitationListener#onInvitationCanceled` which is actually properly handled in this PR (https://github.com/voxeet/voxeet-uxkit-reactnative/pull/43/files#diff-a2454737e03d31608a460a867ac8a4385eee787ee6c165f42e32399a3415faed) line 39

If we keep this new broadcast receiver, it wouldn't work by itself when a cancel request was sent via the internal web socket (but it "works" because of the previous duplicated work -> the later is actually the expected management)

To be more precise, the idea of the native sdk/uxkit are to hide as much as possible the various possible Android specific components to prevent heavy management on the wrapper side. 

I will put some other comments inline into the PR, feel free to comment back as well 👍

**Comment by codlab** [comment]
Thanks for the PR btw, I did not push this forward but it will make us go forward quicker than expected

**Comment by tonydung2011** [comment]
Hi @codlab , can you help me to find the `out.mp3` file. I cannot see it in the original repo

**Comment by codlab** [comment]
This file is unfortunately into the assets folder, can you rename the file to "incoming.mp3" and set it as blank (it seems as well that the file you set in the PR is already blank)? I'll populate it after merge

**Comment by codlab** [comment]
I'm merging it in another branch, I'll do some modification and then merge that finally into develop quite soon. Thanks for the MR ;)

**Pull request merged**
